<?php
$runtimes = $this->getParam('runtimes', []);
$marketplace = $this->getParam('marketplace', []);
?>
<div class="cover">
    <h1 class="zone xl margin-bottom-large">
        <a data-ls-attrs="href=/console/home?project={{router.params.project}}" class="back text-size-small link-return-animation--start"><i class="icon-left-open"></i> Home</a>
        <br />

        <span>Functions</span>
    </h1>
</div>

<div class="zone xl">
    <ul class="phases clear" data-ui-phases data-selected="{{router.params.tab}}">
        <li data-state="/console/functions?project={{router.params.project}}">
            <h2>Functions</h2>

            <div class="zone xl"
                data-service="functions.list"
                data-scope="sdk"
                data-event="load,functions.create,functions.update,functions.delete"
                data-name="project-functions"
                data-param-project-id="{{router.params.project}}"
                data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                data-param-offset=""
                data-param-order-type="DESC"
                data-success="trigger"
                data-success-param-trigger-events="functions.list">

                <div data-ls-if="0 == {{project-functions.functions.length}} || undefined == {{project-functions.functions.length}}" class="box margin-top margin-bottom">
                    <h3 class="margin-bottom-small text-bold">No Functions Found</h3>

                    <p class="margin-bottom-no">You haven't created any functions for your project yet.</p>
                </div>

                <div data-ls-if="0 != {{project-functions.functions.length}}">
                    <div class="margin-bottom-small text-align-end text-size-small margin-top-negative text-fade"><span data-ls-bind="{{project-functions.total}}"></span> functions found</div>

                    <div class="box margin-bottom">
                        <ul data-ls-loop="project-functions.functions" data-ls-as="function" class="list">
                            <li class="clear">
                                <div class="pull-start margin-end avatar-container">
                                    <img src="" data-ls-attrs="src=/images/runtimes/{{function.runtime|runtimeLogo}}?v=<?php echo APP_CACHE_BUSTER; ?>" alt="Function Runtime" class="avatar" loading="lazy" width="60" height="60" />
                                </div>

                                <a data-ls-attrs="href=/console/functions/function?id={{function.$id}}&project={{router.params.project}}" class="button pull-end">Settings</a>

                                <span data-ls-bind="{{function.name}}"></span>

                                <p class="text-fade margin-bottom-no" data-ls-bind="{{function.runtime|runtimeName}} {{function.runtime|runtimeVersion}}"></p>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="pull-end text-align-center paging">
                    <form
                        data-service="functions.list"
                        data-event="submit"
                        data-param-search="{{router.params.search}}"
                        data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                        data-param-order-type="DESC"
                        data-scope="sdk"
                        data-name="project-functions"
                        data-success="state"
                        data-success-param-state-keys="search,offset">
                        <button name="offset" data-paging-back data-offset="{{router.params.offset}}" data-total="{{project-users.total}}" class="margin-end round small" aria-label="Back"><i class="icon-left-open"></i></button>
                    </form>

                    <span data-ls-bind="{{router.params.offset|pageCurrent}} / {{project-functions.total|pageTotal}}"></span>

                    <form
                        data-service="functions.list"
                        data-event="submit"
                        data-param-search="{{router.params.search}}"
                        data-param-limit="<?php echo APP_PAGING_LIMIT; ?>"
                        data-param-order-type="DESC"
                        data-scope="sdk"
                        data-name="project-functions"
                        data-success="state"
                        data-success-param-state-keys="search,offset">
                        <button name="offset" data-paging-next data-offset="{{router.params.offset}}" data-total="{{project-functions.total}}" class="margin-start round small" aria-label="Next"><i class="icon-right-open"></i></button>
                    </form>
                </div>

                <div class="clear">
                    <div data-ui-modal class="modal close box sticky-footer" data-button-text="Add Function">
                        <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                        <h1>Add Function</h1>

                        <form
                            data-analytics
                            data-analytics-activity
                            data-analytics-event="submit"
                            data-analytics-category="console"
                            data-analytics-label="Create Project Function"
                            data-service="functions.create"
                            data-scope="sdk"
                            data-event="submit"
                            data-success="alert,trigger,reset,redirect"
                            data-success-param-alert-text="Created function successfully"
                            data-success-param-trigger-events="functions.create"
                            data-success-param-redirect-url="/console/functions/function?id={{serviceData.$id}}&project={{router.params.project}}"
                            data-failure="alert"
                            data-failure-param-alert-text="Failed to create function"
                            data-failure-param-alert-classname="error">
                            <label for="functionId">Function ID</label>
                            <input
                                type="hidden"
                                data-custom-id
                                data-id-type="auto"
                                data-validator="functions.get"
                                required
                                maxlength="36"
                                pattern="^[a-zA-Z0-9][a-zA-Z0-9._-]{1,36}$"
                                name="functionId" />

                            <label for="name">Name</label>
                            <input type="text" id="name" name="name" required autocomplete="off" class="margin-bottom" maxlength="128" />

                            <label for="runtime">Runtimes</label>
                            <select name="runtime" id="runtime" required class="margin-bottom-xl">
                                <?php foreach ($runtimes as $key => $runtime): ?>
                                    <option value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($runtime['name']); ?> <?php echo $this->escape($runtime['version']); ?></option>
                                <?php endforeach;?>
                            </select>

                            <input id="execute" name="execute" value="" hidden />

                            <footer>
                                <button type="submit">Create</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                            </footer>
                        </form>
                    </div>
                </div>
            </div>
        </li>

        <li data-state="/console/functions?project={{router.params.project}}">
            <h2>Marketplace</h2>

            <h3>Featured</h3>


            <ul class="tiles cell-2 margin-bottom-small">
                <?php foreach($marketplace as $index => $method):
                    $key = ucfirst($method['key'] ?? '');
                    $name = $method['name'] ?? '';
                    $icon = $method['icon'] ?? '';
                    $docs = $method['docs'] ?? '';
                    $enabled = $method['enabled'] ?? false;
                    ?>
                <li class="">
                    <div class="box padding-small margin-bottom clear">
                        <?php if($enabled): ?>
                            <form
                                data-analytics
                                data-analytics-activity
                                data-analytics-event="submit"
                                data-analytics-category="console"
                                data-analytics-label="Update Project Auth Status (<?php echo $this->escape($name); ?>)"
                                data-service="projects.updateAuthStatus"
                                data-scope="console"
                                data-event="change"
                                data-param-project-id="{{router.params.project}}"
                                data-success="alert,trigger"
                                data-success-param-alert-text="Updated project auth status successfully"
                                data-success-param-trigger-events="projects.update"
                                data-failure="alert"
                                data-failure-param-alert-text="Failed to update project auth status settings"
                                data-failure-param-alert-classname="error">
                                <input name="method" id="auth<?php echo $this->escape($key); ?>" type="hidden" autocomplete="off" value="<?php echo $this->escape($index); ?>">
                                <?php if( !(in_array($key, ['usersAuthMagicURL', 'usersAuthInvites']) && !$smtpEnabled)): ?>
                                    <input name="status" type="hidden" data-forms-switch data-ls-bind="{{console-project.auth<?php echo $this->escape($key); ?>}}" data-cast-to="boolean" class="pull-end" />
                                <?php endif; ?>
                            </form>
                        <?php endif; ?>

                        <img src="<?php echo $this->escape($icon); ?>?buster=<?php echo APP_CACHE_BUSTER; ?>" alt="Email/Password Logo" class="pull-start provider margin-end" />

                        <span class="text-size-small"><?php echo $this->escape($name); ?><?php if(!$enabled): ?> <span class="text-fade text-size-xs">soon</span><?php endif; ?>

                        <?php if( in_array($key, ['usersAuthMagicURL', 'usersAuthInvites']) && !$smtpEnabled): ?>
                            <p class="margin-bottom-no text-one-liner text-size-small text-danger">
                                SMTP Disabled
                            </p>
                        <?php else: ?>
                            <?php if($docs): ?>
                            <p class="margin-bottom-no text-one-liner text-size-small">
                                <a href="<?php echo $this->escape($docs); ?>" target="_blank" rel="noopener">Docs<i class="icon-link-ext"></i></a>
                            </p>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </li>
                <?php endforeach;?>
            </ul>

            <!-- <h3>OAuth2 Providers</h3>

            <div class="margin-bottom margin-top"
                data-service="projects.get"
                data-event="load,projects.create,projects.update,projects.deleteProject"
                data-name="console-project"
                data-param-project-id="{{router.params.project}}"
                data-scope="console">
                <ul class="tiles cell-3 margin-bottom-small">
                    <?php foreach ($providers as $provider => $data):
                    if (isset($data['enabled']) && !$data['enabled']) {continue;}
                        if (isset($data['mock']) && $data['mock']) {continue;}
                        $sandbox = $data['sandbox'] ?? false;
                        $form = $data['form'] ?? false;
                        $name = $data['name'] ?? 'Unknown';
                        $beta = $data['beta'] ?? false;
                    ?>
                        <li class="<?php echo (isset($data['enabled']) && !$data['enabled']) ? 'dev-feature' : ''; ?>">
                            <div data-ui-modal class="modal close" data-button-alias="none" data-open-event="provider-update-<?php echo $provider; ?>">
                                <button type="button" class="close pull-end" data-ui-modal-close=""><i class="icon-cancel"></i></button>

                                <h1><?php echo $this->escape($name); ?> <?php if ($sandbox): ?>Sandbox<?php endif;?> OAuth2 Settings</h1>

                                <form
                                    autocomplete="off"
                                    data-analytics
                                    data-analytics-activity
                                    data-analytics-event="submit"
                                    data-analytics-category="console"
                                    data-analytics-label="Update Project OAuth2"
                                    data-service="projects.updateOAuth2"
                                    data-scope="console"
                                    data-event="submit"
                                    data-param-project-id="{{router.params.project}}"
                                    data-success="alert,trigger"
                                    data-success-param-alert-text="Updated project OAuth2 settings successfully"
                                    data-success-param-trigger-events="projects.update"
                                    data-failure="alert"
                                    data-failure-param-alert-text="Failed to update project OAuth2 settings"
                                    data-failure-param-alert-classname="error">

                                    <input style="display: none" type="text" /> <?php /** Disabling Chrone Autofill @see https://stackoverflow.com/a/15917221/2299554 */?>
                                    <input style="display: none" type="password" /> <?php /** Disabling Chrone Autofill @see https://stackoverflow.com/a/15917221/2299554 */?>

                                    <input name="provider" id="provider<?php echo $this->escape(ucfirst($provider)); ?>" type="hidden" autocomplete="off" value="<?php echo $this->escape($provider); ?>">

                                    <?php if (!$form): ?>
                                        <label for="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Appid">App ID</label>
                                        <input name="appId" id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Appid" type="text" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Appid}}">

                                        <label for="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Secret">App Secret</label>
                                        <input name="secret" data-forms-show-secret id="oauth2<?php echo $this->escape(ucfirst($provider)); ?>Secret" type="password" autocomplete="off" data-ls-bind="{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Secret}}">
                                    <?php else: ?>
                                        <?php
                                            $form = new View(__DIR__.'/oauth/'.$this->escape($form));
                                            echo $form
                                                ->setParam("provider", $provider)
                                                ->render();
                                            ?>
                                    <?php endif; ?>

                                    <div class="info row thin margin-bottom margin-top">
                                        <div class="col span-1">
                                            <i class="icon-info-circled text-sign"></i>
                                        </div>
                                        <div class="col span-11">
                                            <p>To complete set up, add this OAuth2 redirect URI to your <?php echo $this->escape(ucfirst($provider)); ?> app configuration.</p>

                                            <div class="input-copy">
                                                <input data-forms-copy type="text" disabled data-ls-bind="{{env.ENDPOINT}}/v1/account/sessions/oauth2/callback/<?php echo $this->escape($provider); ?>/{{router.params.project}}" class="margin-bottom-no" />
                                            </div>
                                        </div>
                                    </div>

                                    <button>Update</button> &nbsp; <button data-ui-modal-close="" type="button" class="reverse">Cancel</button>
                                </form>
                            </div>

                            <div class="box padding-small margin-bottom">
                                <span data-ls-if="
                                    {{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Appid}} &&
                                    {{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Secret}}">
                                    <button class="switch on pull-end" data-ls-ui-trigger="provider-update-<?php echo $provider; ?>"></button>
                                </span>

                                <span data-ls-if="
                                    !{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Appid}} ||
                                    !{{console-project.provider<?php echo $this->escape(ucfirst($provider)); ?>Secret}}">
                                    <button class="switch pull-end" data-ls-ui-trigger="provider-update-<?php echo $this->escape($provider); ?>"></button>
                                </span>

                                <img src="/images/users/<?php echo $this->escape(strtolower($provider)); ?>.png?buster=<?php echo APP_CACHE_BUSTER; ?>" alt="<?php echo $this->escape(ucfirst($provider)); ?> Logo" class="pull-start provider margin-end" />

                                <span class="text-size-small">
                                    <?php echo $this->escape($name); ?> <?php if ($sandbox): ?><span class="text-size-xs text-fade">sandbox</span><?php endif;?> <?php if ($beta): ?><span class="text-size-xs text-fade">beta</span><?php endif;?>
                                </span>

                                <p class="margin-bottom-no text-one-liner text-size-small">
                                    <a href="<?php echo $data['developers']; ?>" target="_blank" rel="noopener">OAuth2 Docs<i class="icon-link-ext"></i></a>
                                </p>
                            </div>
                        </li>
                    <?php endforeach;?>
                </ul>
            </div> -->
            
        </li>

    </ul>
</div>